### ISSUE TITLE
Assumptions

### ISSUE THREAD

**Issue by FedericoTartarini** [CenterForTheBuiltEnvironment/ashrae-db-II#18]
I am proposing the following assumptions. Place a tick if you agree or comment below if you don't.

- [x] if tr is missing but top is available calculating tr with the following equation 2*top - ta
- [x] dropping PMV, PPD, and SET that are in DB II since we do not know which equation they used to calculate them.
- [x] Limit 10 < ta < 40 and dropped those entries which do have not measured ta, since it is pointless to have them
- [x] Limit 0 < met < 4 but kept those entries with met = NaN
- [x] Limit 0 < clo < 4 but kept those entries with met = NaN
- [x] Limit 0 < vel < 4 but kept those entries with met = NaN
- [x] Limit 0 < tr < 50 but kept those entries with met = NaN

**Comment by tom-parkinson** [comment]
Just confirming that the condition is not `met` = NaN in all cases but rather the parameter with limits e.g. 0 < `clo` < 4 but keep those entries with `clo` = NaN. Also confirming that by limit you mean keep records but not calculate `pmv` or `ppd`.

**Comment by FedericoTartarini** [comment]
My plan is to drop all the records that have a value but are outside the above mentioned limits. For example if there is an entry with t = 60, it will be dropped from the database since 60 is higher than 40. On the other hand, if a record does not have information, e.g., met = NaN, it will not be dropped.

On top of that, I will only calculate the PMV, PPD, and SET values when they are within the respective standards applicability limits, which means that if lets say ta = 35C, I will not drop the record but at the same time I will not calculate the PMV since the indoor air temperature is too high. ISO and ASHRAE have different applicability limits. Consequently, that record will have PMV = NaN

**Comment by tom-parkinson** [comment]
Agree with all of the above
