### ISSUE TITLE
Bad entries

### ISSUE THREAD

**Issue by FedericoTartarini** [CenterForTheBuiltEnvironment/ashrae-db-II#9]
I have plotted the TSV vs the air temperature and there are a lot of wrong or meaningless (for the built environment) entries. See a few below. It is not possible that:
1. people feel hot at 0 degC. 
2. Slightly cool at more than 60 degrees
3. Cold at more than 30 deg.C
4. Slightly cool between 40 and 50 degC
Irrespectively of clothing and met. Plus these are such extreme conditions that will never be kept in buildings indoors. I would remove these studies altogether, they are not pertinent in this database in my opinion.

There are a lot of other anomalies that I have not marked, like people feeling Hot at 10 degC. People use this DB to train model but if there are bad data in we get bad models.

![image](https://user-images.githubusercontent.com/40018640/169956242-b70a8f60-036d-49ae-9a5b-3ff26057b900.png)

**Comment by FedericoTartarini** [comment]
I would flag John Stoops entries as problematic since I think he failed to convert his temperatures from F to C. Summary of data from his building below. I am reporting the mean temperature.

|                      |      ta |
|:---------------------|--------:|
| ('John Stoops', 770) | 54.1    |
| ('John Stoops', 771) | 55.95   |
| ('John Stoops', 772) | 59.3333 |

**Comment by FedericoTartarini** [comment]
the study from Hana Pustayova seems a bit strange too since it is improbable that she only measured 4 temperatures in real buildings

![image](https://user-images.githubusercontent.com/40018640/170953469-a5df0673-8368-44c2-a59c-6a3afa8bbf0e.png)

**Comment by FedericoTartarini** [comment]
This person has no data. Very strange

![image](https://user-images.githubusercontent.com/40018640/170953844-a79cedd8-cf5f-47e2-b8d6-8afaaeed580b.png)

**Comment by FedericoTartarini** [comment]
Seeing people feeling hot at 10 C seems a bit odd to me

![image](https://user-images.githubusercontent.com/40018640/170954081-31dedf16-4f70-4706-9d13-3a458803bc64.png)

**Comment by FedericoTartarini** [comment]
This person measured all his data at above 26 C but one point at 14, isn't it very strange?
![image](https://user-images.githubusercontent.com/40018640/170954324-c46080a0-7c74-4afd-91cb-fe346b34b23c.png)

**Comment by FedericoTartarini** [comment]
Fred study has also a problem with `thermal_sensation` and `preference`
![image](https://user-images.githubusercontent.com/40018640/170956132-6007d897-3b60-49fc-bc4f-2ebd57547e2f.png)

**Comment by tom-parkinson** [comment]
Nice work to uncover all these! I wonder if we add a `notes` column to the metadata table where we can briefly describe the dubious things? So for Fred's dataset it could be something like `reversed sensation\preference` and for Ozarisoy it would be `uses integer ta values`. If the dataset looks fine then it would be a `NaN` value in that column so users could filter out dubious datasets.

**Comment by FedericoTartarini** [comment]
I will let you choose what to do, I do not think people will read the notes. It is better if we drop those values or in the main database we add a column which ranks the data quality. My preference would be to drop those studies, we have a lot of data anyway and I am always in favour to have less data but of higher quality, but I will let you decide.

**Comment by tom-parkinson** [comment]
Stoops - here's a screen grab from his thesis. There's no way to reconcile these values with what we are seeing in those data, so let's drop it
<img width="757" alt="Screen Shot 2022-05-31 at 9 28 30 AM" src="https://user-images.githubusercontent.com/40145982/171226009-93c2e149-6120-4369-898d-e47202b95117.png">

**Comment by tom-parkinson** [comment]
Pustayova - again, hard to reconcile those integer values with what is reported in (what I think is) the paper. Let's flag these values.
<img width="533" alt="Screen Shot 2022-05-31 at 9 33 04 AM" src="https://user-images.githubusercontent.com/40145982/171226853-2f4296d8-ae92-416c-bb14-e93f03a39519.png">

**Comment by tom-parkinson** [comment]
Kwok - same as above. Let's flag it.
<img width="673" alt="Screen Shot 2022-05-31 at 9 35 19 AM" src="https://user-images.githubusercontent.com/40145982/171227405-c4c2fa0e-43ec-409a-95be-e3e7c10c171a.png">

**Comment by tom-parkinson** [comment]
Adebamowo - drop the 14C value

**Comment by tom-parkinson** [comment]
Ozarisoy - we have no way of disproving the `thermal_sensation` votes, but we can flag the use of integer values in the quality field we're creating.

**Comment by FedericoTartarini** [comment]
Shall we drop the data or flag them as `low` quality? If we drop them, shall we drop all the data from their studies or just the data with anomalies? I would prefer not to touch the original data. We should either drop them or mark them as `low quality`, consequently I would drop the thermal_preference data from Fred's study. The rationale is that if we drop the data there are not really any major draw back, just the database will be a little smaller, but if we start editing the raw data:
1. in the future may be hard to track the changes
2. we may inadvertently make a wrong assumption and create `bad` data.

I propose to:
- Stoops drop all the strange data, that may have been measured in F
- Hana Pustayova - drop all the data since it is not acceptable to measure T with a less than 1 degC resolution
- Kwok Alison - drop all the data since it is not acceptable to measure T with a less than 1 degC resolution
- Adebamovo - drop all data since TS vs TP makes no sense and there is a strange data point at 14 C
- Ozarisoy - drop all the data since it is not acceptable to measure T with a less than 1 degC resolution
- Fred - drop all the thermal_preference data since they are incorrect
- I would also suggest to drop all the other studies, that I have not listed here, that measured T with a less than 1 degC resolution. I think this is fair since both Standards require to measure temperature with a higher accuracy. I will look for these studies.

What do you think?

**Comment by FedericoTartarini** [comment]
I agree with you about the terminology. Practically, It would be better to have the `quality_assurance` column in the database file rather than in the metadata since many people will miss it there. But I agree that the column should be added to the metadata file.

Will you:
- [ ] add the column `quality_assurance` to the metadata file?
- [ ] address your bullet points you listed in your previous message?
Please update the file called `db_measurements_v2.0.1.csv`

I will then re-run my code and calculate the PMV/PPD/.... values.
